# Generated by Django 4.1.7 on 2023-03-30 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignatureData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Firstname", models.CharField(max_length=100)),
                ("Middlename", models.CharField(max_length=100)),
                ("Lastname", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=100)),
                ("ContactNumber", models.CharField(max_length=100)),
                ("Address", models.CharField(max_length=100)),
                ("SignaturesID", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
